apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-java-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: server
  template:
    metadata:
      labels:
        service: server
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: init-permissions
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              set -eux;
              mkdir -p /data/h2;
              chmod -R 0777 /data;
          volumeMounts:
            - name: app-data
              mountPath: /data
      containers:
        - name: server-service
          image: rajnigupta21/test-first
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: h2file
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: app-data
              mountPath: /data
      volumes:
        # For local clusters (kind/minikube/microk8s), you can use a hostPath to share
        # the same directory with your local machine. Ensure the path exists on the node.
        # Warning: hostPath is suitable for local/dev only.
        - name: app-data
          hostPath:
            path: /tmp/test-first-data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    service: server
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001